[package]
name = "key_gen"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
edition = "2018"

[dependencies]
bitcoin_support  = { path = "../bitcoin_support" }
ethereum_support = { path = "../ethereum_support" }
hex = "0.4"
secp256k1_keypair = { path = "../secp256k1_keypair" }
tiny-keccak = "1.5.0"
