[package]
name = "trading_client"
version = "0.1.0"
authors = [
    "Thomas Eizinger <thomas@coblox.tech>",
    "Philipp Hoenisch <philipp@coblox.tech>",
    "Franck Royer <franck@coblox.tech>",
    "Lloyd Fournier <lloyd@coblox.tech>",
]

[dependencies]
structopt = "0.2.8"
serde = "1.0.64"
serde_json = "1.0.19"
serde_derive = "1.0.63"
reqwest = "0.8.5"
lazy_static = "1.0.1"
regex = "1.0.0"
uuid = { version = "0.6.3", features = ["serde", "v4"] }
web3 = "0.3.0"
bitcoin_rpc = { path = "../../vendor/bitcoin_rpc" }
common_types = { path = "../common_types"}
ethereum_support = { path = "../../vendor/ethereum_support" }
bitcoin_support = { path = "../../vendor/bitcoin_support" }
