[package]
name = "siren"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
edition = "2018"

[dependencies]
derivative = "1.0.3"
http = "0.1.19"
readonly = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
spectral = "0.6.0"
