[comit]
secret_seed = "f87165e305b0f7c4824d3806434f9d0909610a25641ab8773cf92a48c9d77670"

[network]
listen = [
    "/ip4/0.0.0.0/tcp/9938"
]

[http_api]
address="0.0.0.0"
port=8000

[btsieve]
url = "http://localhost:8181"

[btsieve.bitcoin]
poll_interval_secs = 1
network = "regtest"

[btsieve.ethereum]
poll_interval_secs = 1
network = "regtest"
