language: rust
cache: cargo
sudo: required
rust: nightly-2018-06-24
install: true
services:
  - docker
before_script:
- "./setup.sh"
script:
- "./check-fmt.sh"
- cargo build --verbose
- cargo test --all -- --test-threads=20
notifications:
  email: false
  slack:
    rooms:
      - tenx-company:buMm6Pg6Sbhljx2HRLwNC44z#coblox-swap-bots
    on_success: always
    on_failure: always
    on_pull_requests: true
