language: rust
cache:
  directories:
  - "$HOME/.rustup"
  - "$HOME/.cargo"
  - "$HOME/.cache/sccache"
sudo: required
rust: nightly-2018-09-14
addons:
  apt:
    packages:
    - libzmq3-dev
install: true
services:
- docker
env:
  global:
  - COMIT_NODE_CONFIG_PATH=./application/comit_node/config #TODO rethink if this is here needed
  - RUST_LOG=testcontainers=debug,bitcoin_rpc=debug
  - RUST_BACKTRACE=full
  - BITCOIND_ADDITIONAL_SLEEP_PERIOD=500
  - KEEP_CONTAINERS=true
  - RUST_TEST_THREADS=8 # Even though we only have 2 cores on Travis, we mostly wait for containers in our tests. Doing that in parallel saves us some time! (8 is just an arbitrary number!)
before_script:
- docker pull trufflesuite/ganache-cli:v6.1.3
- docker pull coblox/bitcoin-core:0.16.1-r2
- "./setup.sh"
- which sccache || cargo install sccache
script:
- "./check-fmt.sh"
- cargo clippy
- RUSTC_WRAPPER=~/.cargo/bin/sccache cargo build --all
- RUSTC_WRAPPER=~/.cargo/bin/sccache cargo test --all
- LOG_SERVICES=1 ./run_environments/regtest/harness.sh ./run_environments/regtest/happy_path.sh
notifications:
  email: false
  slack:
    rooms:
    - tenx-company:buMm6Pg6Sbhljx2HRLwNC44z#coblox-bots
    on_success: never
    on_failure: always
    on_pull_requests: true
