language: rust
cache:
  cargo: true
  directories:
  - "$HOME/.rustup"
  timeout: 300
sudo: required
rust: nightly-2018-06-24
before_install:
- openssl aes-256-cbc -K $encrypted_13ab58161701_key -iv $encrypted_13ab58161701_iv -in .travis/gcloud-authentication.json.enc -out .travis/gcloud-authentication.json -d
install: true
services:
- docker
env:
  global:
  - RUST_LOG=testcontainers=debug,testcontainers::wait_for_message=trace,bitcoin_rpc=debug
  - RUST_BACKTRACE=full
  - BITCOIND_ADDITIONAL_SLEEP_PERIOD=500
  - KEEP_CONTAINERS_AFTER_TEST=true
before_script:
- docker pull trufflesuite/ganache-cli:v6.1.3
- docker pull ruimarinho/bitcoin-core:0.16.0
- "./setup.sh"
- ".travis/capture-docker-traffic.sh"
script:
- "./check-fmt.sh"
- cargo build --all
- cargo test --all
after_script:
- expr $TRAVIS_TEST_RESULT > /dev/null && .travis/upload-container-logs-to-gcs.sh
notifications:
  email: false
  slack:
    rooms:
    - tenx-company:buMm6Pg6Sbhljx2HRLwNC44z#coblox-swap-bots
    on_success: always
    on_failure: always
    on_pull_requests: true
