[workspace]

members = [
    "application/bitcoin_htlc",
    "application/bitcoin_wallet",
    "application/common_types",
    "application/ethereum_htlc",
    "application/ethereum_wallet",
    "application/comit_node",
    "application/logging",
    "application/comit_node_client",
    "application/ledger_query_service",
    "application/ganp",
    "vendor/bitcoin_rpc_test_helpers",
    "vendor/bitcoin_support",
    "vendor/ethereum_support",
    "vendor/ganache_rust_web3",
    "vendor/tc_web3_client",
    "vendor/tc_bitcoincore_client",
    "vendor/key_gen",
    "vendor/lightning_rpc",
    "vendor/event_store",
    "vendor/transport_protocol",
]
