[package]
name = "nectar"
version = "0.1.0"
authors = ["CoBloX Team <team@coblox.tech>"]
edition = "2018"

[dependencies]
anyhow = "1"
async-trait = "0.1"
# TODO: Get comit to re-export it so that we do not have to sync updates
bitcoin = { version = "0.23.0", features = ["rand"] }
chrono = "0.4"
comit = { git = "https://github.com/comit-network/comit-rs", package = "comit", branch = "nectar" }
futures = "0.3.5"
lazy_static = "1.4"
reqwest = "0.10.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.18"
strum_macros = "0.18"
thiserror = "1.0"
tracing = "0.1.15"

[dependencies.rand]
default-features = false
version = "0.6"

[dev-dependencies]
testcontainers = "0.9"
tokio = { version = "0.2.21", features = ["macros"] }

[features]
default = ["test-docker"]

# "test-docker" feature is related to test code
# if it's enabled then tests needing docker will be ran
test-docker = []
