[package]
authors = ["CoBloX developers <team@coblox.tech>"]
name = "comit"
version = "0.1.0"
edition = "2018"
description = "Core components of the COMIT protocol"

[dependencies]
anyhow = "1"
async-trait = "0.1"
base64 = "0.12.3"
bitcoin = { version = "0.23.0", features = ["rand"] }
blockchain_contracts = "0.3.2"
chrono = { version = "0.4", features = ["serde"] }
derivative = "2"
digest = { path = "../digest" }
ethbloom = "0.9.1"
futures = "0.3.5"
genawaiter = { version = "0.99", features = ["futures03"] }
hex = "0.4"
lazy_static = "1"
levenshtein = "1"
libp2p = { version = "0.18", default-features = false, features = ["tcp", "secio", "yamux", "mplex"] }
lru = "0.5.2"
num = "0.3"
primitive-types = { version = "0.7.2", features = ["serde"] }
rand = "0.7"
reqwest = { version = "0.10.6", default-features = false, features = ["json", "native-tls"] }
serde = "1"
serde-hex = "0.1.0"
serde_json = "1"
serdebug = "1"
sha2 = "0.9"
strum = "0.18.0"
strum_macros = "0.18.0"
thiserror = "1"
tokio = { version = "0.2.21", features = ["sync"] }
tracing = "0.1.15"
tracing-futures = { version = "0.2", features = ["std-future", "futures-03"] }
uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies]
bitcoincore-rpc = "0.11.0"
proptest = "0.10.0"
spectral = { version = "0.6", default-features = false }
testcontainers = "0.9"
tokio = { version = "0.2.21", features = ["macros"] }
