version: '3'
services:
  treasury_service:
    build: ../../fake_treasury_service
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - RUST_LOG=info,fake_treasury_service=debug
      - RATE=0.07543
    ports:
    - "8020:8000"
  exchange_service:
    build: ../../exchange_service
    env_file:
      - "$SWAP_ENV/testnet.env"
      - ./network.env
    environment:
      - TREASURY_SERVICE_URL=http://treasury_service:8000
      - ROCKET_ADDRESS=0.0.0.0
      - RUST_LOG=info,exchange_service=debug
      - RUST_BACKTRACE=1
    ports:
    - "8010:8000"
    depends_on:
    - treasury_service
  trading_service:
    build: ../../trading_service
    env_file:
      - "$SWAP_ENV/testnet.env"
      - ./network.env
    environment:
      - EXCHANGE_SERVICE_URL=http://exchange_service:8000
      - ROCKET_ADDRESS=0.0.0.0
      - RUST_LOG=info,trading_service=debug
      - RUST_BACKTRACE=1
    ports:
    - "8000:8000"
