[package]
name = "bitcoin_support"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
edition = "2018"

[dependencies]
bigdecimal = "0.1.0"
bitcoin = { version = "0.19.1", features = ["use-serde"] }
hex = "0.4"
lazy_static = "1"
secp256k1_omni_context = { path = "../secp256k1_omni_context" }
serde = { version = "1", features = ["derive"] }
strum = "0.16"
strum_macros = "0.16"

[dev-dependencies]
serde_json = "1"
spectral = "0.6"
