version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
