version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
    ignored_updates:
      # as per https://github.com/comit-network/comit-rs/issues/1316
      - match:
          dependency_name: "primitive-types"
      - match:
          dependency_name: "rlp"
      # we only depend on ethbloom to access certain types. our version needs to match whichever version web3 is transitively bringing in
      - match:
          dependency_name: "ethbloom"
      # we only depend on `libsqlite3-sys` directly to activate the "bundled" feature. the version we are using has to match the one that diesel is depending on, hence bumping it manually is pointless.
      - match:
          dependency_name: "libsqlite3-sys"
  - package_manager: "javascript"
    directory: "/api_tests"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
