[package]
name = "btsieve"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
edition = "2018"

[dependencies]
bitcoin_rpc_client = "0.5"
bitcoin_support = { path = "../../vendor/bitcoin_support" }
byteorder = "1.2"
config = { version = "0.9", features = ["toml"] }
directories = "1.0"
debug_stub_derive = "0.3"
ethbloom = "0.5"
ethereum_support = { path = "../../vendor/ethereum_support" }
ethereum-types = "0.4"
failure = "0.1"
futures = "0.1"
hex = "0.3"
http = "0.1"
http-api-problem = "0.12"
hyper = "0.12"
itertools = "0.8"
log = "0.4"
pretty_env_logger = "0.2"
serde = "1"
serde_derive = "1"
serde_json = "1"
tokio = "0.1"
url = "1.7"
warp = "0.1"
zmq-rs = "0.1"
derivative = "1"

[dev-dependencies]
env_logger = "0.5"
hex = "0.3"
rand = "0.3"
secp256k1_support = { path = "../../vendor/secp256k1_support" }
spectral = "0.6"
tc_web3_client = { path = "../../vendor/tc_web3_client" }
testcontainers = "0.6"
