[package]
authors = ["CoBloX developers <team@coblox.tech>"]
edition = "2018"
name = "btsieve"
version = "0.1.0"

[dependencies]
bitcoincore-rpc = "0.6"
byteorder = "1.2"
chrono = { version = "0.4", features = ["serde"] }
debug_stub_derive = "0.3"
derivative = "1"
directories = "2.0"
ethbloom = "0.5"
failure = "0.1"
futures = "0.1"
hex = "0.3"
http = "0.1"
http-api-problem = "0.13"
hyper = "0.12"
itertools = "0.8"
log = "0.4"
pretty_env_logger = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "0.2"
tokio = "0.1"
url = "1.7"
url_serde = "0.2.0"
warp = "0.1"
zmq-rs = "0.1"

[dependencies.bitcoin_support]
path = "../vendor/bitcoin_support"

[dependencies.config]
features = ["toml"]
version = "0.9"

[dependencies.ethereum_support]
path = "../vendor/ethereum_support"

[dependencies.fern]
features = ["colored"]
version = "0.5"

[dev-dependencies]
env_logger = "0.6"
hex = "0.3"
rand = "0.6"
spectral = "0.6"
testcontainers = "0.7"

[dev-dependencies.secp256k1_support]
path = "../vendor/secp256k1_support"

[dev-dependencies.tc_web3_client]
path = "../vendor/tc_web3_client"
