[package]
name = "blockchain_contracts"
version = "0.1.0"
authors = ["CoBloX developers <team@coblox.tech>"]
edition = "2018"

[dependencies]
bitcoin = "0.18.0"
bitcoin_hashes = "0.3.2"
bitcoin_witness = { path = "../../internal/bitcoin_witness" }
byteorder = "1.3"
hex = "0.3"
hex-literal = "0.2"
itertools = "0.8.0"
lazy_static = "1"
regex = "1.2"
rust-crypto = "0.2"
secp256k1 = { version = "0.12", features = ["rand"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.15"
strum_macros = "0.15"
tiny-keccak = "1.5"
web3 = "0.8"

[dev-dependencies]
bitcoin_quantity = { git = "https://github.com/coblox/bitcoin-quantity", features = ["serde"] }
bitcoincore-rpc = "0.7"
failure = "0.1"
lazy_static = "1.3"
log = "0.4"
pretty_env_logger = "0.3"
spectral = "0.6"
testcontainers = "0.7"
tiny-keccak = "1.5"

# These versions need to be changed together with web3, depends on what version of primitive-types ships with web3
[dev-dependencies.primitive-types]
features = ["rlp"]
version = "0.3.0"

[dev-dependencies.rlp]
version = "0.4.2"

[build-dependencies]
regex = "1.2"
