[package]
authors = ["CoBloX developers <team@coblox.tech>"]
name = "cnd"
version = "0.2.0"
edition = "2018"
description = "Reference implementation of a COMIT network daemon."

[dependencies]
binary_macros = "0.6"
bitcoin_support = { path = "../internal/bitcoin_support" }
bitcoin_witness = { path = "../internal/bitcoin_witness" }
blockchain_contracts = { path = "../blockchain_contracts" }
chrono = { version = "0.4", features = ["serde"] }
comit_i = { path = "../internal/comit_i" }
config = { version = "0.9", features = ["toml"] }
debug_stub_derive = "0.3"
derivative = "1"
diesel = { version = "1.4", features = ["sqlite"] }
diesel_migrations = "1.4.0"
directories = "2.0"
either = "1.5"
enum-display-derive = "0.1"
ethereum_support = { path = "../internal/ethereum_support" }
failure = "0.1"
fern = { version = "0.5", features = ["colored"] }
futures = "0.1"
hex = "0.3"
hex-serde = "0.1.0"
http = "0.1"
http-api-problem = "0.13"
hyper = "0.12"
lazy_static = "1"
libp2p = { version = "0.12" }
libp2p-comit = { path = "../libp2p-comit" }
log = { version = "0.4", features = ["serde"] }
maplit = "1"
mime = "0.3"
mime_guess = "2.0"
rand = "0.7"
reqwest = { version = "0.9", default-features = false }
rlp = "0.4"
rust-crypto = "0.2"
rustic_hal = "0.2"
secp256k1_keypair = { path = "../internal/secp256k1_keypair" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
siren = { path = "../internal/siren" }
state_machine_future = { version = "0.2" }
structopt = "0.3"
strum = "0.15"
strum_macros = "0.15"
tokio = "0.1"
toml = "0.5"
url_serde = "0.2.0"
uuid = { version = "0.7", features = ["serde", "v4"] }
void = "1.0.2"
warp = { version = "0.1", default-features = false }

[dev-dependencies]
bitcoin_rpc_test_helpers = { path = "../internal/bitcoin_rpc_test_helpers" }
bitcoincore-rpc = "0.8.0-rc1"
key_gen = { path = "../internal/key_gen" }
maplit = "1"
matches = "0.1.8"
memsocket = "0.1"
pretty_env_logger = "0.3"
quickcheck = "0.9.0"
quickcheck_macros = "0.8.0"
regex = "1.3.1"
serde_urlencoded = "0.6"
spectral = "0.6"
tempfile = "3.1.0"
tiny-keccak = "1.5"
