[package]
authors = ["CoBloX developers <team@coblox.tech>"]
name = "cnd"
version = "0.5.0"
edition = "2018"
description = "Reference implementation of a COMIT network daemon."

[dependencies]
anyhow = "1"
async-std = { version = "1", features = ["unstable"] }
async-trait = "0.1"
bigdecimal = "0.1.0"
bitcoin = { version = "0.19.1", features = ["use-serde"] }
blockchain_contracts = "0.1"
byteorder = "1.3"
chrono = { version = "0.4", features = ["serde"] }
config = { version = "0.10", features = ["toml"] }
derivative = "1"
derive_more = "0.99.2"
diesel = { version = "1.4", features = ["sqlite", "chrono"] }
diesel_migrations = "1.4.0"
directories = "2.0"
either = "1.5"
ethbloom = "0.6.4"
fern = { version = "0.5", features = ["colored"] }
futures = { version = "0.1" }
futures-core = { version = "=0.3.0-alpha.19", features = ["alloc", "compat", "async-await"], package = "futures-preview" }
hex = "0.4"
hex-serde = "0.1.0"
http-api-problem = "0.13"
lazy_static = "1"
libp2p = { version = "0.13" }
libp2p-comit = { path = "../libp2p-comit" }
libp2p-core = { version = "0.13" }
libsqlite3-sys = { version = ">=0.8.0, <0.13.0", features = ["bundled"] }
log = { version = "0.4", features = ["serde"] }
mime = "0.3"
mime_guess = "2.0"
num = "0.2"
paste = "0.1"
pem = "0.7"
rand = "0.7"
regex = "1.3"
reqwest = { version = "0.9", default-features = false }
rust-crypto = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
siren = { version = "0.1", package = "siren-types" }
state_machine_future = { version = "0.2" }
structopt = "0.3"
strum = "0.16"
strum_macros = "0.16"
testcontainers = "0.8"
thiserror = "1"
tiny-keccak = { version = "2.0", features = ["keccak"] }
tokio = "0.1"
toml = "0.5"
url_serde = "0.2.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
void = "1.0.2"
warp = { version = "0.1", default-features = false }

# These versions need to be "in sync".
# web3 0.8 gives us primitive-types 0.3.0
# primitive-types 0.3.0 with the "rlp" feature gives us "rlp" version 0.4.2
[dependencies.web3]
default-features = false
features = ["http"]
version = "0.8"

[dependencies.primitive-types]
features = ["rlp"]
version = "0.3.0"

[dependencies.rlp]
version = "0.4.2"

[dev-dependencies]
base64 = "0.11"
bitcoincore-rpc = "0.8.0-rc1"
matches = "0.1.8"
quickcheck = "0.9.0"
serde_urlencoded = "0.6"
spectral = "0.6"
tempfile = "3.1.0"
