# This file only works in combination with an additional keyfile, e.g. in development.toml
[ethereum]
network_id = 1
node_url = "http://localhost:8545"
gas_price=2_000_000_000

[bitcoin]
network_id = "BTC_REGTEST"
satoshi_per_byte = 50 # used for calculating transaction fees
node_url = "http://localhost:18443"
node_username = "bitcoin"
node_password = "54pLR_f7-G6is32LP-7nbhzZSbJs_2zSATtZV_r05yg="

[comit]
remote_comit_node_url = "0.0.0.0:8010"
comit_listen = "0.0.0.0:8011"

[http_api]
address="0.0.0.0"
port=8000
logging=true
