[comit]
secret_seed = "c1fd6fc5bde7fee2c2fb6d868dc0f40368051fede1d83f814839d562c210aa27"

[log_levels]
comit_node="DEBUG"

[network]
listen = [
    "/ip4/0.0.0.0/tcp/8011"
]

[http_api]
address="0.0.0.0"
port=8000

[btsieve]
url = "http://localhost:8001"

[btsieve.bitcoin]
poll_interval_secs = 300
network = "regtest"

[btsieve.ethereum]
poll_interval_secs = 20
network = "regtest"

[web_gui]
address="0.0.0.0"
port=8080
