[package]
authors = ["CoBloX developers <team@coblox.tech>"]
name = "comit_node"
version = "0.1.0"
edition = "2018"

[build-dependencies]
regex = "1"

[dependencies]
binary_macros = "0.6"
bitcoin_rpc_client = "0.6"
chrono = { version = "0.4", features = ["serde"] }
config = { version = "0.9", features = ["toml"] }
debug_stub_derive = "0.3"
derivative = "1"
directories = "1.0"
either = "1.5"
enum-display-derive = "0.1"
failure = "0.1"
futures = "0.1"
hex = "0.3"
http = "0.1"
http-api-problem = "0.12"
hyper = "0.12"
log = "0.4"
maplit = "1"
mime = "0.3"
mime_guess = "1.8"
rand = "0.4"
reqwest = "0.9"
rlp = "0.3"
rust-crypto = "0.2"
rustic_hal = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = "0.15"
strum_macros = "0.15"
tokio = "0.1"
url = "1.7"
url_serde = "0.2.0"
warp = "0.1"
hex-serde = "0.1.0"
libp2p = "0.6.0"
void = "1.0.2"

[dependencies.bam]
path = "../../vendor/bam"

[dependencies.bitcoin_rpc_test_helpers]
path = "../../vendor/bitcoin_rpc_test_helpers"

[dependencies.bitcoin_support]
path = "../../vendor/bitcoin_support"

[dependencies.bitcoin_witness]
path = "../../vendor/bitcoin_witness"

[dependencies.comit_i]
path = "../../vendor/comit_i"

[dependencies.ethereum_support]
path = "../../vendor/ethereum_support"

[dependencies.fern]
features = ["colored"]
version = "0.5"

[dependencies.secp256k1_support]
path = "../../vendor/secp256k1_support"

[dependencies.state_machine_future]
version = "0.2"

[dependencies.tc_bitcoincore_client]
path = "../../vendor/tc_bitcoincore_client"

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.6"

[dev-dependencies]
lazy_static = "1"
maplit = "1"
memsocket = "0.1"
pretty_env_logger = "0.2"
spectral = "0.6"
tiny-keccak = "1.4"
testcontainers = "0.7"
serde_urlencoded = "0.5"

[dev-dependencies.key_gen]
path = "../../vendor/key_gen"

[dev-dependencies.tc_web3_client]
path = "../../vendor/tc_web3_client"
