[package]
name = "comit_node"
version = "0.1.0"
authors = [
    "Thomas Eizinger <thomas@coblox.tech>",
    "Philipp Hoenisch <philipp@coblox.tech>",
    "Franck Royer <franck@coblox.tech>",
    "Lloyd Fournier <lloyd@coblox.tech>",
]

[dependencies]
bitcoin_rpc_client = "0.1"
bitcoin_htlc = { path = "../bitcoin_htlc" }
debug_stub_derive = "0.3.0"
reqwest = "0.8.6"
serde = "1.0.66"
serde_derive = "1.0.66"
lazy_static = "1"
log = "0.4.3"
web3 = "0.4"
uuid = { version = "0.6.5", features = ["serde", "v4"] }
rocket = "0.3"
rocket_contrib = "0.3"
rocket_codegen = "0.3"
common_types = { path = "../common_types" }
bitcoin_support  = { path = "../../vendor/bitcoin_support" }
bitcoin_witness = { path = "../../vendor/bitcoin_witness" }
secp256k1_support = { path = "../../vendor/secp256k1_support" }
http-api-problem = { version = "0.7", features = ["with_rocket", "with_hyper"] }
serde_json = "1.0.22"
ethereum_wallet = { path = "../ethereum_wallet" }
ethereum_support = { path = "../../vendor/ethereum_support" }
hex = "0.3.2"
tiny-keccak = "1.4.2"
logging = { path = "../logging" }
event_store = { path = "../../vendor/event_store" }
rand = "0.4.2"
rustc-hex = "1.0.0"
transport_protocol = { path = "../../vendor/transport_protocol" }
tokio = "^0.1.11"
futures = "0.1"
chrono = "0.4.2"
gotham = { git = "https://github.com/gotham-rs/gotham.git" }
gotham_derive = { git = "https://github.com/gotham-rs/gotham.git" }
hyper = "0.12"
mime = "0.3"
comit_wallet = { path = "../comit_wallet" }
config = "0.9"

[dev-dependencies]
maplit = "1"
memsocket = "0.1"
pretty_env_logger = "0.2"
tc_parity_parity = "0.1"
tc_web3_client = { path = "../../vendor/tc_web3_client" }
testcontainers = "0.2"
spectral = "0.6"
lazy_static = "1"
key_gen = { path = "../../vendor/key_gen"}

[build-dependencies]
regex = "1.0.0"
