[package]
name = "ethereum_support"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
edition = "2018"

[dependencies]
bigdecimal = "0.1.0"
byteorder = "1.3"
lazy_static = "1"
num = "0.2"
regex = "1.3"
secp256k1_omni_context = { path = "../secp256k1_omni_context" }
serde = { version = "1", features = ["derive"] }
strum = "0.16"
strum_macros = "0.16"
tiny-keccak = "1.5"

# These versions need to be "in sync".
# web3 0.8 gives us primitive-types 0.3.0
# primitive-types 0.3.0 with the "rlp" feature gives us "rlp" version 0.4.2
[dependencies.extern_web3]
default-features = false
features = ["http"]
package = "web3"
version = "0.8"

[dependencies.primitive-types]
features = ["rlp"]
version = "0.3.0"

[dependencies.rlp]
version = "0.4.2"

[dev-dependencies]
hex = "0.4"
serde_json = "1"
spectral = "0.6"
