[package]
name = "ethereum_htlc"
version = "0.1.0"
authors = ["Thomas Eizinger <thomas@eizinger.io>"]

[dependencies]
web3 = "0.3.0"
hex = "0.3.2"
ganache_rust_web3 = { path = "../ganache_rust_web3" }
log = "0.4.1"
chrono = "0.4.2"
env_logger = "0.5.10"

[build-dependencies]
regex = "1.0.0"
